# =============================================================================
# Composite Action: Setup comfy-test environment
# =============================================================================
# This action sets up everything needed to run comfy-test:
# - Python
# - Playwright browser (CACHED to save ~2-3 min per run)
# - uv (fast pip replacement)
# - comfy-test itself
#
# Usage in workflow:
#   - uses: ./.comfy-test-src/.github/actions/setup
#     with:
#       python-version: "3.11"
# =============================================================================

name: Setup comfy-test environment
description: Sets up Python, Playwright (cached), and comfy-test

inputs:
  python-version:
    description: "Python version to use"
    required: true
  comfy-test-path:
    description: "Path to comfy-test checkout"
    default: "./.comfy-test-src"

runs:
  using: composite
  steps:
    # -------------------------------------------------------------------------
    # Step 1: Setup Python
    # -------------------------------------------------------------------------
    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    # -------------------------------------------------------------------------
    # Step 2: Cache Playwright browser
    # -------------------------------------------------------------------------
    # Playwright downloads ~250MB chromium browser. Caching saves 2-3 min.
    # Cache key is per-OS since browser binaries are platform-specific.
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
          ~/Library/Caches/ms-playwright
          ~/AppData/Local/ms-playwright
        key: playwright-${{ runner.os }}-chromium

    # -------------------------------------------------------------------------
    # Step 3: Install uv (fast pip replacement)
    # -------------------------------------------------------------------------
    - name: Install uv
      shell: bash
      run: pip install uv

    # -------------------------------------------------------------------------
    # Step 4: Install comfy-test (ALWAYS FRESH - not cached)
    # -------------------------------------------------------------------------
    # We install from the checkout, not from cache, so changes to comfy-test
    # are picked up immediately.
    - name: Install comfy-test
      shell: bash
      run: pip install "${{ inputs.comfy-test-path }}[screenshot]"

    # -------------------------------------------------------------------------
    # Step 5: Install Playwright browser
    # -------------------------------------------------------------------------
    # If cached, this just verifies the browser exists (~1 sec).
    # If not cached, downloads chromium (~2-3 min).
    # install-deps installs system dependencies (apt/brew) - can't be cached.
    - name: Install Playwright
      shell: bash
      run: |
        playwright install chromium
        # install-deps may fail on some systems (e.g., macOS), that's ok
        playwright install-deps chromium || true
