# =============================================================================
# Composite Action: Setup ComfyUI test environment
# =============================================================================
# Sets up everything needed EXCEPT comfy-test itself:
# - Python + pip cache
# - ComfyUI clone + requirements
# - Playwright browser
#
# Cached: ComfyUI clone/portable, Playwright browser
# Always runs: pip install (fast due to pip download cache)
# =============================================================================

name: Setup ComfyUI test environment
description: Sets up Python, ComfyUI, and Playwright (cached)

inputs:
  python-version:
    description: "Python version to use"
    required: true
  platform:
    description: "Target platform (linux, macos, windows, windows-portable)"
    default: ""

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'

    - name: Restore environment cache
      id: env-cache
      uses: actions/cache/restore@v4
      with:
        path: |
          .comfy-test-env
          ~/.cache/ms-playwright
          ~/Library/Caches/ms-playwright
          ~/AppData/Local/ms-playwright
        key: comfy-env-${{ runner.os }}-py${{ inputs.python-version }}-${{ inputs.platform || 'standard' }}

    - name: Clone/download ComfyUI
      if: steps.env-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p .comfy-test-env
        if [ "${{ inputs.platform }}" = "windows-portable" ]; then
          echo "Downloading ComfyUI Portable..."
          curl -L --fail -o .comfy-test-env/portable.7z \
            "https://github.com/comfyanonymous/ComfyUI/releases/latest/download/ComfyUI_windows_portable_nvidia.7z"
          echo "Extracting..."
          "/c/Program Files/7-Zip/7z.exe" x .comfy-test-env/portable.7z -o".comfy-test-env" -y
          rm .comfy-test-env/portable.7z
        else
          echo "Cloning ComfyUI..."
          git clone --depth 1 https://github.com/comfyanonymous/ComfyUI.git .comfy-test-env/ComfyUI
        fi

    - name: Install pip packages
      if: inputs.platform != 'windows-portable'
      shell: bash
      run: |
        echo "Installing ComfyUI requirements..."
        pip install -r .comfy-test-env/ComfyUI/requirements.txt
        echo "Installing uv and playwright..."
        pip install uv playwright

    - name: Install Playwright browser
      if: steps.env-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        playwright install chromium
        playwright install-deps chromium || true

    - name: Save environment cache
      if: steps.env-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          .comfy-test-env
          ~/.cache/ms-playwright
          ~/Library/Caches/ms-playwright
          ~/AppData/Local/ms-playwright
        key: comfy-env-${{ runner.os }}-py${{ inputs.python-version }}-${{ inputs.platform || 'standard' }}
