# =============================================================================
# Composite Action: Setup ComfyUI test environment
# =============================================================================
# Sets up everything needed EXCEPT comfy-test itself:
# - Python + venv with all dependencies
# - ComfyUI clone + requirements
# - Playwright browser
#
# Cached: ~/venv (venv + ComfyUI + Playwright browser)
# On cache hit: instant - no pip install needed
# =============================================================================

name: Setup ComfyUI test environment
description: Sets up Python, ComfyUI, and Playwright (cached in venv)

inputs:
  python-version:
    description: "Python version to use"
    required: true
  platform:
    description: "Target platform (linux, macos, windows, windows-portable)"
    default: ""

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Restore environment cache
      id: env-cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/venv
          ~/.cache/ms-playwright
          ~/Library/Caches/ms-playwright
          ~/AppData/Local/ms-playwright
        key: comfy-env-v3-${{ runner.os }}-py${{ inputs.python-version }}-${{ inputs.platform || 'standard' }}

    - name: Setup environment (cache miss)
      if: steps.env-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p ~/venv

        # Create venv
        echo "Creating venv..."
        python -m venv ~/venv/venv

        # Activate venv (cross-platform)
        if [ -f ~/venv/venv/bin/activate ]; then
          source ~/venv/venv/bin/activate
        else
          source ~/venv/venv/Scripts/activate
        fi

        # Install uv first (bootstrap)
        echo "Installing uv..."
        pip install uv

        # Clone/download ComfyUI
        if [ "${{ inputs.platform }}" = "windows-portable" ]; then
          echo "Downloading ComfyUI Portable..."
          curl -L --fail -o ~/venv/portable.7z \
            "https://github.com/comfyanonymous/ComfyUI/releases/latest/download/ComfyUI_windows_portable_nvidia.7z"
          echo "Extracting..."
          "/c/Program Files/7-Zip/7z.exe" x ~/venv/portable.7z -o"$HOME/venv" -y
          rm ~/venv/portable.7z
        else
          echo "Cloning ComfyUI..."
          git clone --depth 1 https://github.com/comfyanonymous/ComfyUI.git ~/venv/ComfyUI
          echo "Installing ComfyUI requirements..."
          uv pip install -r ~/venv/ComfyUI/requirements.txt
        fi

        # Install playwright
        echo "Installing playwright..."
        uv pip install playwright

        # Install Playwright browser
        echo "Installing Playwright browser..."
        playwright install chromium
        playwright install-deps chromium || true

    - name: Activate venv (cache hit)
      if: steps.env-cache.outputs.cache-hit == 'true'
      shell: bash
      run: |
        echo "Cache hit - venv ready to use"
        # Add venv to PATH for subsequent steps
        if [ -d ~/venv/venv/bin ]; then
          echo "$HOME/venv/venv/bin" >> $GITHUB_PATH
        else
          echo "$HOME/venv/venv/Scripts" >> $GITHUB_PATH
        fi

    - name: Add venv to PATH (cache miss)
      if: steps.env-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        if [ -d ~/venv/venv/bin ]; then
          echo "$HOME/venv/venv/bin" >> $GITHUB_PATH
        else
          echo "$HOME/venv/venv/Scripts" >> $GITHUB_PATH
        fi

    - name: Save environment cache
      if: steps.env-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          ~/venv
          ~/.cache/ms-playwright
          ~/Library/Caches/ms-playwright
          ~/AppData/Local/ms-playwright
        key: comfy-env-v3-${{ runner.os }}-py${{ inputs.python-version }}-${{ inputs.platform || 'standard' }}
