# =============================================================================
# Composite Action: Setup comfy-test environment
# =============================================================================
name: Setup comfy-test environment
description: Sets up Python, Playwright (cached), and comfy-test

inputs:
  python-version:
    description: "Python version to use"
    required: true
  comfy-test-path:
    description: "Path to comfy-test checkout"
    default: "./.comfy-test-src"
  platform:
    description: "Target platform (linux, macos, windows, windows-portable)"
    default: ""

runs:
  using: composite
  steps:
    # === RESTORE CACHES ===
    - name: Restore Playwright cache
      id: playwright-cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cache/ms-playwright
          ~/Library/Caches/ms-playwright
          ~/AppData/Local/ms-playwright
        key: playwright-${{ runner.os }}-chromium

    - name: Restore pip cache
      id: pip-cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cache/pip
          ~/Library/Caches/pip
          ~/AppData/Local/pip/Cache
        key: pip-${{ runner.os }}-py${{ inputs.python-version }}

    - name: Restore Portable cache
      if: inputs.platform == 'windows-portable'
      id: portable-cache
      uses: actions/cache/restore@v4
      with:
        path: ~/.comfy-test/cache/portable
        key: comfyui-portable-${{ runner.os }}

    # === SETUP ===
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      shell: bash
      run: pip install uv

    - name: Install Playwright browser
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        pip install playwright
        playwright install chromium
        playwright install-deps chromium || true

    - name: Download and extract Portable
      if: inputs.platform == 'windows-portable' && steps.portable-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        CACHE_DIR="$HOME/.comfy-test/cache/portable"
        mkdir -p "$CACHE_DIR"
        VERSION=$(curl -s https://api.github.com/repos/comfyanonymous/ComfyUI/releases/latest | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
        echo "Latest version: $VERSION"
        ARCHIVE="$CACHE_DIR/ComfyUI_portable_${VERSION}.7z"
        EXTRACT_DIR="$CACHE_DIR/ComfyUI_portable_${VERSION}"
        if [ ! -f "$ARCHIVE" ]; then
          echo "Downloading..."
          curl -L -o "$ARCHIVE" "https://github.com/comfyanonymous/ComfyUI/releases/download/${VERSION}/ComfyUI_windows_portable_nvidia.7z"
        fi
        if [ ! -d "$EXTRACT_DIR" ] || [ -z "$(ls -A "$EXTRACT_DIR" 2>/dev/null)" ]; then
          echo "Extracting..."
          mkdir -p "$EXTRACT_DIR"
          7z x "$ARCHIVE" -o"$EXTRACT_DIR" -y
        fi
        echo "Portable ready at: $EXTRACT_DIR"

    # === SAVE CACHES ===
    - name: Save Playwright cache
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.cache/ms-playwright
          ~/Library/Caches/ms-playwright
          ~/AppData/Local/ms-playwright
        key: playwright-${{ runner.os }}-chromium

    - name: Save pip cache
      if: steps.pip-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.cache/pip
          ~/Library/Caches/pip
          ~/AppData/Local/pip/Cache
        key: pip-${{ runner.os }}-py${{ inputs.python-version }}

    - name: Save Portable cache
      if: inputs.platform == 'windows-portable' && steps.portable-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ~/.comfy-test/cache/portable
        key: comfyui-portable-${{ runner.os }}

    # === INSTALL COMFY-TEST (after caches saved) ===
    - name: Install comfy-test
      shell: bash
      run: pip install "${{ inputs.comfy-test-path }}[screenshot]"
