# =============================================================================
# Composite Action: Setup comfy-test environment
# =============================================================================
# This action sets up everything needed to run comfy-test:
# - Python
# - uv (fast pip replacement)
# - Playwright browser (CACHED to save ~2-3 min per run)
# - comfy-test itself
#
# Usage in workflow:
#   - uses: ./.comfy-test-src/.github/actions/setup
#     with:
#       python-version: "3.11"
# =============================================================================

name: Setup comfy-test environment
description: Sets up Python, Playwright (cached), and comfy-test

inputs:
  python-version:
    description: "Python version to use"
    required: true
  comfy-test-path:
    description: "Path to comfy-test checkout"
    default: "./.comfy-test-src"

runs:
  using: composite
  steps:
    # -------------------------------------------------------------------------
    # Step 1: Setup Python
    # -------------------------------------------------------------------------
    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    # -------------------------------------------------------------------------
    # Step 2: Install uv (fast pip replacement)
    # -------------------------------------------------------------------------
    - name: Install uv
      shell: bash
      run: pip install uv

    # -------------------------------------------------------------------------
    # Step 3: Cache Playwright browser
    # -------------------------------------------------------------------------
    # Playwright downloads ~250MB chromium browser. Caching saves 2-3 min.
    # Cache key is per-OS since browser binaries are platform-specific.
    - name: Get Playwright cache path
      id: playwright-cache
      shell: bash
      run: |
        if [ "$RUNNER_OS" = "Windows" ]; then
          # Use forward slashes for bash compatibility
          echo "path=$(echo $LOCALAPPDATA | sed 's/\\/\//g')/ms-playwright" >> $GITHUB_OUTPUT
        elif [ "$RUNNER_OS" = "macOS" ]; then
          echo "path=$HOME/Library/Caches/ms-playwright" >> $GITHUB_OUTPUT
        else
          echo "path=$HOME/.cache/ms-playwright" >> $GITHUB_OUTPUT
        fi

    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: ${{ steps.playwright-cache.outputs.path }}
        key: playwright-${{ runner.os }}-chromium

    # -------------------------------------------------------------------------
    # Step 4: Install comfy-test
    # -------------------------------------------------------------------------
    - name: Install comfy-test
      shell: bash
      run: pip install "${{ inputs.comfy-test-path }}[screenshot]"

    # -------------------------------------------------------------------------
    # Step 5: Install Playwright browser
    # -------------------------------------------------------------------------
    # If cached, this just verifies the browser exists (~1 sec).
    # If not cached, downloads chromium (~2-3 min).
    - name: Install Playwright
      shell: bash
      run: |
        playwright install chromium
        # install-deps installs system dependencies - can fail on some systems
        playwright install-deps chromium || true
