# Generated by `comfy-test vm build --unattended`. Do not edit by hand.
# Placeholders (<<NAME>>) are substituted by _unattend.py.
#
# State machine: each stage advances C:\comfy-setup\state.txt and either
# falls through to the next stage in the same invocation, or schedules a
# reboot via HKLM RunOnce and exits.
#
# Final stage writes C:\setup-complete and runs Stop-Computer. The host
# (`comfy-test vm build --unattended`) polls Get-VM | State for "Off"
# and uses that as the success signal.

$ErrorActionPreference = "Stop"
$ProgressPreference    = "SilentlyContinue"  # speeds Invoke-WebRequest ~10x

$SetupDir   = "C:\comfy-setup"
$StateFile  = Join-Path $SetupDir "state.txt"
$LogFile    = Join-Path $SetupDir "setup.log"
$ScriptPath = $MyInvocation.MyCommand.Path
if (-not $ScriptPath) { $ScriptPath = Join-Path $SetupDir "post-install.ps1" }

if (-not (Test-Path $SetupDir)) { New-Item -Path $SetupDir -ItemType Directory -Force | Out-Null }

function Log($msg) {
    $line = "{0}  {1}" -f (Get-Date -Format "yyyy-MM-dd HH:mm:ss"), $msg
    Add-Content -Path $LogFile -Value $line
    Write-Host $line
}

function Save-State($name) {
    Set-Content -Path $StateFile -Value $name -Encoding ASCII
}

function Schedule-NextBoot() {
    Set-ItemProperty `
        -Path  "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce" `
        -Name  "ComfyPostInstall" `
        -Value ("powershell.exe -ExecutionPolicy Bypass -NoProfile " +
                "-WindowStyle Hidden -File `"$ScriptPath`"")
}

function Download-File($url, $dest) {
    Log "  download $url -> $dest"
    Invoke-WebRequest -Uri $url -OutFile $dest -UseBasicParsing
}

# --- Stages ----------------------------------------------------------------

function Stage-DefenderTweaks {
    Log "[stage1] defender + IO tweaks"
    function Try-Run($cmd) { try { & $cmd } catch { Log "  (skip) $($_.Exception.Message)" } }
    Try-Run { Set-MpPreference -DisableRealtimeMonitoring $true }
    Try-Run { Set-MpPreference -DisableArchiveScanning $true }
    Try-Run { Set-MpPreference -DisableScriptScanning $true }
    Try-Run { Set-MpPreference -DisableScanningNetworkFiles $true }
    Try-Run { Set-MpPreference -DisableIOAVProtection $true }
    Try-Run { Set-MpPreference -DisableBehaviorMonitoring $true }
    Try-Run { Set-MpPreference -MAPSReporting 0 }
    Try-Run {
        Add-MpPreference -ExclusionProcess @(
            'python.exe','pip.exe','uv.exe','node.exe','ComfyUI.exe'
        )
    }
    Try-Run {
        Add-MpPreference -ExclusionPath @(
            "$env:USERPROFILE\Documents\ComfyUI",
            "$env:USERPROFILE\.comfy-test-cache",
            "$env:LOCALAPPDATA\pip\Cache",
            "$env:LOCALAPPDATA\uv\cache",
            "C:\actions-runner"
        )
    }
    Try-Run {
        New-ItemProperty `
            -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' `
            -Name LongPathsEnabled -Value 1 -PropertyType DWORD -Force | Out-Null
    }
    Log "[stage1] done"
}

function Stage-InstallNvidia {
    Log "[stage2] install NVIDIA driver"
    $exe = Join-Path $SetupDir "nvidia-driver.exe"
    Download-File "<<NVIDIA_DRIVER_URL>>" $exe
    Log "  running $exe -s -noreboot"
    # NVIDIA installer exit codes: 0 = OK, 1 = OK reboot required.
    # We're rebooting anyway.
    $p = Start-Process -FilePath $exe -ArgumentList "-s","-noreboot" -Wait -PassThru
    Log "  installer exit: $($p.ExitCode)"
    Log "[stage2] done; rebooting to register driver"
}

function Stage-InstallPython {
    Log "[stage3] install Python 3.12"
    $exe = Join-Path $SetupDir "python-installer.exe"
    Download-File "<<PYTHON_URL>>" $exe
    Log "  running silent install"
    $p = Start-Process -FilePath $exe `
        -ArgumentList "/quiet","InstallAllUsers=1","PrependPath=1","Include_test=0","Include_launcher=1" `
        -Wait -PassThru
    if ($p.ExitCode -ne 0) { throw "Python installer exit $($p.ExitCode)" }

    # Refresh PATH for this session (the installer set the machine PATH but
    # the current process doesn't pick that up automatically).
    $env:Path = [Environment]::GetEnvironmentVariable("Path","Machine") + ";" +
                [Environment]::GetEnvironmentVariable("Path","User")
    Log "[stage3] done"
}

function Find-Python {
    foreach ($p in @(
        "C:\Program Files\Python312\python.exe",
        "C:\Program Files (x86)\Python312\python.exe"
    )) { if (Test-Path $p) { return $p } }
    $cmd = Get-Command python.exe -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    throw "python.exe not found after install"
}

function Stage-InstallComfyTest {
    Log "[stage4] install comfy-test + uv"
    $py = Find-Python
    Log "  using $py"
    & $py -m pip install --upgrade pip      | ForEach-Object { Log "  $_" }
    & $py -m pip install --upgrade comfy-test uv | ForEach-Object { Log "  $_" }
    if ($LASTEXITCODE -ne 0) { throw "pip install failed: $LASTEXITCODE" }
    Log "[stage4] done"
}

function Stage-InstallComfyDesktop {
    Log "[stage5] install ComfyUI Desktop"
    $exe = Join-Path $SetupDir "ComfyUI-Setup.exe"
    Download-File "<<COMFY_DESKTOP_URL>>" $exe
    Log "  running silent install"
    $p = Start-Process -FilePath $exe -ArgumentList "/S" -Wait -PassThru
    Log "  installer exit: $($p.ExitCode)"
    Log "[stage5] done"
}

function Stage-MountSharedFolder {
    # Mount the host SMB share as Z: for the ci-runner profile, persistent.
    # No-op when the host opted out of --shared-folder (UNC is empty).
    $unc  = '<<SHARED_FOLDER_UNC>>'
    $user = '<<SHARED_FOLDER_USER>>'
    $pwd  = '<<SHARED_FOLDER_PASSWORD>>'
    if (-not $unc) {
        Log "[stage6] no shared folder configured; skipping Z: mount"
        return
    }
    Log "[stage6] mounting $unc as Z: (persistent, user $user)"
    $sec = ConvertTo-SecureString $pwd -AsPlainText -Force
    $cred = New-Object System.Management.Automation.PSCredential($user, $sec)
    # New-PSDrive -Persist makes the mapping survive reboots for the
    # current user. -Scope Global keeps it visible after the function
    # returns (PSDrive scope defaults to Local otherwise).
    try {
        New-PSDrive -Name Z -PSProvider FileSystem -Root $unc `
                    -Credential $cred -Persist -Scope Global -ErrorAction Stop | Out-Null
        Log "  Z: mounted -> $unc"
    } catch {
        Log "  WARN: New-PSDrive failed ($($_.Exception.Message)); falling back to net use"
        # Fallback: net use (no PSCredential, but works on older PS).
        & net.exe use Z: $unc /user:$user $pwd /persistent:yes | ForEach-Object { Log "    $_" }
        if ($LASTEXITCODE -ne 0) { Log "  FALLBACK ALSO FAILED (exit $LASTEXITCODE); continuing without Z:" }
    }
}

function Stage-ConfigureRunner {
    # Skip when the host opted out (--no-runner, or runner-url/token not
    # provided). RUNNER_URL is the empty string in that case.
    $runnerUrl = '<<RUNNER_URL>>'
    if (-not $runnerUrl) {
        Log "[stage7] no runner URL configured; skipping GHA runner setup"
        Log "[stage7] (re-run host-side with --runner-url + --runner-token-env "
        Log "          to add a runner later; or register manually inside the VM)"
        return
    }
    Log "[stage7] configure GHA runner"
    $runnerDir = "C:\actions-runner"
    if (-not (Test-Path $runnerDir)) {
        New-Item -Path $runnerDir -ItemType Directory -Force | Out-Null
    }
    $zip = Join-Path $SetupDir "actions-runner.zip"
    $url = "https://github.com/actions/runner/releases/download/v<<RUNNER_VERSION>>/actions-runner-win-x64-<<RUNNER_VERSION>>.zip"
    Download-File $url $zip
    Log "  extracting to $runnerDir"
    Expand-Archive -Path $zip -DestinationPath $runnerDir -Force

    Log "  registering with GitHub"
    Push-Location $runnerDir
    try {
        # Note: NO --runasservice. The runner runs inside the autologon
        # user's interactive desktop session via a Startup folder shortcut.
        # Services run in Session 0 with no interactive desktop, which
        # breaks chromium / Electron / ComfyUI Desktop GUI tests.
        & .\config.cmd `
            --url "<<RUNNER_URL>>" `
            --token "<<RUNNER_TOKEN>>" `
            --name "$env:COMPUTERNAME" `
            --labels "self-hosted,windows,cuda,desktop" `
            --unattended `
            --replace
        if ($LASTEXITCODE -ne 0) { throw "runner config exit $LASTEXITCODE" }
    } finally {
        Pop-Location
    }

    Log "  installing Startup-folder launcher"
    $startup = [Environment]::GetFolderPath("Startup")
    $lnkPath = Join-Path $startup "GHA Runner.lnk"
    $wsh     = New-Object -ComObject WScript.Shell
    $lnk     = $wsh.CreateShortcut($lnkPath)
    $lnk.TargetPath       = Join-Path $runnerDir "run.cmd"
    $lnk.WorkingDirectory = $runnerDir
    $lnk.WindowStyle      = 7  # minimized
    $lnk.Save()

    Log "[stage6] done"
}

# --- Driver ----------------------------------------------------------------

try {
    $state = if (Test-Path $StateFile) { (Get-Content $StateFile -Raw).Trim() } else { "stage1" }
    Log "==== post-install entry; state=$state ===="

    while ($state -ne "done") {
        switch ($state) {
            "stage1" {
                Stage-DefenderTweaks
                $state = "stage2"; Save-State $state
            }
            "stage2" {
                Stage-InstallNvidia
                $state = "stage3"; Save-State $state
                Schedule-NextBoot
                Log "==== rebooting; will resume at stage3 ===="
                Restart-Computer -Force
                # Restart-Computer is asynchronous — exit so we don't fall
                # through to the next stage before the box restarts.
                exit 0
            }
            "stage3" {
                Stage-InstallPython
                $state = "stage4"; Save-State $state
            }
            "stage4" {
                Stage-InstallComfyTest
                $state = "stage5"; Save-State $state
            }
            "stage5" {
                Stage-InstallComfyDesktop
                $state = "stage6"; Save-State $state
            }
            "stage6" {
                Stage-MountSharedFolder
                $state = "stage7"; Save-State $state
            }
            "stage7" {
                Stage-ConfigureRunner
                $state = "done"; Save-State $state
            }
            default {
                throw "unknown state: $state"
            }
        }
    }

    Log "==== all stages complete; writing C:\setup-complete and shutting down ===="
    New-Item -Path "C:\setup-complete" -ItemType File -Force | Out-Null
    Stop-Computer -Force
}
catch {
    Log "FATAL: $($_.Exception.Message)"
    Log "$($_.ScriptStackTrace)"
    # Do NOT shut down on failure — leaving the VM running lets the host
    # poll time out (its success signal is "VM is Off"). User can then
    # connect via vmconnect.exe, read $LogFile, and resume by re-running
    # the script (state.txt records where we stopped).
    exit 1
}
