name: Test Installation
on:
  push:
    branches: [main, dev]
    paths-ignore:
      - '**.md'
      - 'pyproject.toml'
      - 'LICENSE'
      - '.github/workflows/publish.yml'

jobs:
  approve:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - run: echo "Approved"
  test:
    needs: approve
    uses: PozzettiAndrea/comfy-test/.github/workflows/test-matrix.yml@v0.2.6
    with:
      config-file: "comfy-test.toml"
